# BuildMC-Core-Plugin Configuration
# Join our discord server https://discord.gg/p8wBMZXAfb

spawn-elytra:
  # Enable or Disable the spawn elytra feature
  enabled: true # Default: true
  # The strength of the spawn elytra boost
  strength: 5 # Default: 5
  # Should the use of firework rockets with the spawn elytra be blocked?
  disable-rockets: true # Default: true
  # Disable gliding for players when joining. Used to prevent bugs.
  # Shouldn't be disabled! Only if you really have to
  on-join-elytra-check: true # Default: true
  # The Zone in which you can use the spawn elytra
  # You are able to set the elytra zone using the command '/buildmc elytrazone setup ...'
  zone:
    world:
    pos1:
      x:
      y:
      z:
    pos2:
      x:
      y:
      z:


status:
  # If players should be able to use the '/status' command
  enabled: true # Default: true


# The End-Event settings
# Use '/buildmc endevent allow true/false' to set if players should be able to enter the end dimension
end-event:
  # NOTE: Can be overwritten by the '/buildmc endevent' command
  allow-end: false # Default: false

  # List of entity types that should be blocked from going through end portals.
  # Done to prevent destruction of the spawn
  blocked-entities:
    - TNT
    - TNT_MINECART
    - CREEPER


# Some sounds that are used generally
sounds:
  mistake: "minecraft:block.note_block.snare" # Default: "minecraft:block.note_block.snare"
  success: "minecraft:block.note_block.bell" # Default: "minecraft:block.note_block.bell"
  notification: "minecraft:entity.item.pickup" # Default: "minecraft:entity.item.pickup"
  ui:
    click: "minecraft:ui.button.click" # Default: "minecraft:ui.button.click"

# World spawn teleport command
# Players require the default permission 'buildmc.allow-spawn-teleport' to use this command!
spawn-teleport:
  # If true, players can use the '/spawn' command to teleport to the world spawn of the current dimension.
  # Players have to stand still for a certain number of seconds defined in 'wait-for'.
  enabled: true # Default: true

  # The amount of seconds the player has to stand still to get teleported.
  # Set to 0 or smaller to disable.
  wait-for: 8 # Default: 8


# Here are all settings related to claims.
# A player can use the claim-tool to select an area to claim.
# There are 4 types of claims:
#   - Player: A claim by a single person.
#   - Team: A claim by an entire team that anyone in that team can manage.
#   - Server: A claim made by an admin that only players that are admin can manage.
#             Players can also be whitelisted to bypass the protections.
#   - Placeholder: A claim made by admins that has no features.
#                  A Placeholder claim is used to make a certain area unclaimable by others (e.g. public areas).
# Players can use the '/claim ...' command to create, remove and manage claims.
# On Claims, players who aren't whitelisted or the owner of the claim, can't do anything the claim owner blocked.
claims:
  # If true, players can manage their team claims using '/claim ...'.
  enabled: true # Default: true

  # The amount of chunks each player can claim
  player-max-chunk-claim-amount: 256 # Default: 256
  # The amount of chunks each team can claim
  team-max-chunk-claim-amount: 1024 # Default: 1024

  # Settings related to the claim-tool. The claim-tool (if enabled) can be obtained using '/claim claimtool'
  tool:
    # The item used for the claim-tool
    # You are able to define custom item components inside the metadata of the item.
    tool-item:
      DataVersion: 4556
      id: minecraft:carrot_on_a_stick
      count: 1
      schema_version: 1

    # Custom Serialized data that is applied to the claim tool.
    # Should
    tool-item-data: null # Default: null

    # If true, players even with permissions can't get the claim-tool using '/claim claimtool'
    enable-give-command: true # Default: true

    # Limits the maximum size in chunks of the selection
    # If smaller than 0, the limit will be disabled
    limit-selection: 10 # Default: 10

  # Here you can set a whitelist or blacklist for where players are allowed to claim areas.
  # Players can bypass this list when given the permission 'buildmc.bypass-claim-dimension-list'
  dimensions:
    # If true, the list below will block certain dimensions.
    # If false, the list below will only allow to be claimed in the given dimensions.
    blacklist: true # Default: true
    list:
      # Example: - "minecraft:the_end"

  # Hides all protections from all players.
  # Can be used if players should only be able to use the default protections.
  hide-all-protections: false # Default: false

  # What aspects are protected when claimed
  protections:
    # Players cannot break blocks
    player-break:
      default: true
      is-hidden: false
    # Players cannot place blocks
    player-place:
      default: true
      is-hidden: false

    # Players cannot place entities (armor stands, boats, minecarts, and end crystals.)
    player-place-entity:
      default: true
      is-hidden: false

    # Players cannot open containers (e.g. Chests, Barrels...)
    containers:
      default: true
      is-hidden: false

    # Players cannot pick up items
    item-pickup:
      default: false
      is-hidden: false

    # Players cannot drop items
    item-drop:
      default: false
      is-hidden: false

    # Players cannot edit signs
    sign-editing:
      default: true
      is-hidden: false

    # Players can't use splash potions
    splash-potions:
      default: true
      is-hidden: false

    # Players can't enter vehicles
    vehicle-enter:
      default: false
      is-hidden: false

    # Players can't use buckets
    bucket-usage:
      default: true
      is-hidden: false

    # Players can't use frost walker enchantment
    frostwalker:
      default: true
      is-hidden: false

    # Players can't trigger sculk sensors
    sculk-sensor:
      default: true
      is-hidden: false

    # Prevents pistons from moving into claims and pulling out of claims
    piston-movement-across-claim-borders:
      default: true
      is-hidden: false

    # Prevents placing and destroying entities like item frames or paintings
    hanging-entities:
      default: true
      is-hidden: false

    # Interaction related protections
    interactions:
      jukebox:
        default: true
        is-hidden: false

      buttons-and-levers:
        default: false
        is-hidden: false

      # Includes Repeaters, Comparators, and daylight-sensors
      redstone-components:
        default: true
        is-hidden: false

      pressure-plates-and-tripwire:
        default: false
        is-hidden: false

      # Includes Fence Gates, Trapdoors and doors
      doors:
        default: false
        is-hidden: false

      # Disables jumping on farmland
      farmland:
        default: true
        is-hidden: false

      item-frame:
        default: true
        is-hidden: false
      campfire:
        default: true
        is-hidden: false
      bells:
        default: true
        is-hidden: false
      attach-leash:
        default: true
        is-hidden: false
      bone-meal:
        default: true
        is-hidden: false
      beehives:
        default: true
        is-hidden: false
      name-tag:
        default: true
        is-hidden: false
      candles:
        default: true
        is-hidden: false
      light-tnt:
        default: true
        is-hidden: false
      armor-stands:
        default: true
        is-hidden: false
      tame-entity:
        default: true
        is-hidden: false
      shear-entity:
        default: true
        is-hidden: false

    projectile-interactions:
      default: true
      is-hidden: false

    fishing:
      default: true
      is-hidden: false

    # Damage related protections
    damage:
      # Cancels all damage dealt by players to protected entities
      entity-damage:
        default: true
        is-hidden: false
      # Allows players to be damaged by other players
      player-friendly-fire:
        default: true
        is-hidden: false

      # Blocks cannot be destroyed from explosions
      explosion-block-damage:
        default: true
        is-hidden: false
      # Entities cannot get damage from explosions
      explosion-entity-damage:
        default: true
        is-hidden: false

    # Entities in entity-modifications cannot modify blocks
    entity-modifications:
        default: false
        is-hidden: true

  # Settings for claim logs
  logs:
    enabled: true
    rotation-time: "00:00" # When to rotate logs (24h format)
    retention-days: 14 # How many days of logs to keep (set to -1 to disable limit)
    mirror-to-console: false # If the events should be printed into the console


disable-commands: true
disabled-commands:
  # Reload commands. WE DO NOT RECOMMEND USING THIS COMMAND. PLEASE RESTART THE SERVER.
  - "bukkit:reload"
  - "bukkit:rl"
  - "bukkit:bukkitreload"

  # Seed command. This is done to prevent the seed from being accessible, even to admins.
  - "minecraft:seed"

  # Dangerous server control
  - "minecraft:save-off"

player-head:
  # When true, players will drop their head on death.
  on-death: true # Default: true
