# BuildMC-Core-Plugin Configuration
# Join our discord server https://discord.gg/p8wBMZXAfb

spawn-elytra:
  # Enable or Disable the spawn elytra feature
  enabled: true # Default: true
  # The strength of the spawn elytra boost
  strength: 5 # Default: 5
  # Should the use of firework rockets with the spawn elytra be blocked?
  disable-rockets: true # Default: true
  # Disable gliding for players when joining. Used to prevent bugs.
  # Shouldn't be disabled! Only if you really have to
  on-join-elytra-check: true # Default: true
  # The Zone in which you can use the spawn elytra
  # You are able to set the elytra zone using the command '/buildmc elytrazone setup ...'
  zone:
    world:
    pos1:
      x:
      y:
      z:
    pos2:
      x:
      y:
      z:


status:
  # If players should be able to use the '/status' command
  enabled: true # Default: true


# The End-Event settings
# Use '/buildmc endevent allow true/false' to set if players should be able to enter the end dimension
end-event:
  # NOTE: Can be overwritten by the '/buildmc endevent' command
  allow-end: false # Default: false

  # List of entity types that should be blocked from going through end portals.
  # Done to prevent destruction of the spawn
  blocked-entities:
    - TNT
    - TNT_MINECART
    - CREEPER


# Some sounds that are used generally
sounds:
  mistake: "minecraft:block.note_block.snare" # Default: "minecraft:block.note_block.snare"
  success: "minecraft:block.note_block.bell" # Default: "minecraft:block.note_block.bell"


# Here are all settings related to team claims.
# A team can use the claim-tool or the '/buildmc claim ...' command to create or remove their claims.
# On Claims, things like any explosion, withers, block breaking or opening containers don't work.
# Team players can give other players access to their claims using '/buildmc claim allow <player name>'.
claims:
  # If true, players can manage their team claims using '/claim ...'.
  # Admins can also set certain regions as server-claims that no one can do anything in
  enabled: true # Default: true

  # If true, all claim data will be writen to disk when the server saves the overworld.
  # Only change this to false if you really need to
  save-on-world-save: true # Default: true

  # The amount of chunks each team can claim
  max-chunk-claim-amount: 1024 # Default: 1024

  # Settings related to the claim-tool. The claim-tool (if enabled) can be obtained using '/buildmc claimtool'
  tool:
    # The item used for the claim-tool
    tool-item: "carrot_on_a_stick" # Default: "carrot_on_a_stick"

    # The item model id used for the 'minecraft:item_model' component of the tools.
    # Use 'null' for the default minecraft item model.
    # NOTE: Every player needs a custom resourcepack for your custom models to work.
    item-model-id: "null" # Default: "null"
    remove-item-model-id: "null" # Default: "null"

    # If true, the selection and remove tool will require the player to right-click instead of sneak-clicking to set the second position.
    # NOTE: This will not change the '/claim help' text or the lore of the claim selection and remove tool.
    #       You have to manually change them inside the language files.
    use-right-instead-of-sneak-click: false # Default: false

    # If true, players even without permissions can get the claim-tools using '/claim claimtool' or '/claim removetool'
    enable-give-command: true # Default: true

    # Limits the maximum size in chunks of the selection.
    # The limit is disabled if lower than zero.
    limit-selection: 8 # Default: 8

  # What aspects are protected when claimed
  protections:
    # Players cannot break blocks
    player-break: true # Default: true
    # Players cannot place blocks
    player-place: true # Default: true

    # Players cannot open containers (e.g. Chests, Barrels...)
    # Players are still able to open their ender chests or read books in lecterns.
    # But players can't take books from lecterns in others claims.
    containers: true # Default: true

    # Players cannot pick up items
    item-pickup: false # Default: false

    # Players cannot drop items
    item-drop: false # Default: false

    # Players cannot edit signs
    sign-editing: true # Default: true

    # Players can't use splash potions
    splash-potions: true # Default: true

    # Players can't enter vehicles
    vehicle-enter: true # Default: true

    # Players can't use buckets
    bucket-usage: true # Default: true

    # Players can't use frost walker enchantment
    frostwalker: true # Default: true

    # Prevents pistons from moving into claims and pulling out of claims
    piston-movement-across-claim-borders: true # Default: true

    # Prevents end-crystals from being spawned in claims.
    # This also suppresses end-crystals of the owners of the claim.
    end-crystal-place: true # Default: true

    # Prevents entities from being tamed on others claims.
    entity-tame: true # Default: true

    # Players cannot interact with the things listed in "interactions"
    prevent-interactions: true # Default: true
    # Interaction related protections
    interactions:
      # A list of blocks players can't interact with
      # NOTE: You do not have to write all block ids in only upper-case letters
      blocks:
        - COMPARATOR
        - REPEATER
        - LEVER
        - BAMBOO_BUTTON
        - BIRCH_BUTTON
        - ACACIA_BUTTON
        - CHERRY_BUTTON
        - JUNGLE_BUTTON
        - CRIMSON_BUTTON
        - DARK_OAK_BUTTON
        - MANGROVE_BUTTON
        - OAK_BUTTON
        - PALE_OAK_BUTTON
        - POLISHED_BLACKSTONE_BUTTON
        - SPRUCE_BUTTON
        - STONE_BUTTON
        - WARPED_BUTTON
        - CAULDRON
        - LAVA_CAULDRON
        - POWDER_SNOW_CAULDRON
        - BEACON
        - BEEHIVE
        - BEE_NEST
        - RESPAWN_ANCHOR
        - JUKEBOX
        - CAMPFIRE
        - SOUL_CAMPFIRE
        - DECORATED_POT
        - DAYLIGHT_DETECTOR
        - NOTE_BLOCK
        - CHISELED_BOOKSHELF
        - FLOWER_POT
        - SPAWNER
        - TNT
        - CANDLE
        - BLACK_CANDLE
        - WHITE_CANDLE
        - CYAN_CANDLE
        - BLUE_CANDLE
        - BROWN_CANDLE
        - GRAY_CANDLE
        - GREEN_CANDLE
        - LIGHT_BLUE_CANDLE
        - LIGHT_GRAY_CANDLE
        - LIME_CANDLE
        - MAGENTA_CANDLE
        - ORANGE_CANDLE
        - PINK_CANDLE
        - PURPLE_CANDLE
        - RED_CANDLE
        - YELLOW_CANDLE

      # Includes Doors, Trapdoors and Fence-Gates
      doors: true # Default: true

      # This disables the ability to destroy farmland by jumping on it
      farmland: true # Default: true

      attach-leash: true # Default: true
      bone-meal: true # Default: true
      nametags: true # Default: true
      item-frames: true # Default: true
      paintings: true # Default: true
      armor-stands: true # Default: true

    # Damage related protections
    damage:
      # Cancels all damage dealt by players to protected entities
      entity-damage: true # Default: true

      # Blocks cannot be destroyed from explosions
      explosion-block-damage: true # Default: true
      # Entities cannot get damage from explosions
      explosion-entity-damage: true # Default: true

    # Entities in entity-modifications cannot modify blocks
    prevent-entity-modifications: true # Default: true
    entity-modifications:
      wither: true # Default: true
      enderman: false # Default: false
      ravager: false # Default: false


disable-commands: true # Default: true
disabled-commands:
  # Reload commands. WE DO NOT RECOMMEND USING THIS COMMAND. PLEASE RESTART THE SERVER.
  - "bukkit:reload"
  - "bukkit:rl"
  - "bukkit:bukkitreload"

  # Seed command. This is done to prevent the seed from being accessible, even to admins.
  - "minecraft:seed"

  # Dangerous server control
  - "minecraft:save-off"

player-head:
  # When true, players will drop their head on death.
  on-death: true # Default: true