# BuildMC-Core-Plugin Configuration
# Join our discord server https://discord.gg/p8wBMZXAfb

spawn-elytra:
  # Enable or Disable the spawn elytra feature
  enabled: true # Default: true
  # The strength of the spawn elytra boost
  strength: 5 # Default: 5
  # Should the use of firework rockets with the spawn elytra be blocked?
  disable-rockets: true # Default: true
  # Disable gliding for players when joining. Used to prevent bugs.
  # Shouldn't be disabled! Only if you really have to
  on-join-elytra-check: true # Default: true
  # The Zone in which you can use the spawn elytra
  # You are able to set the elytra zone using the command '/buildmc elytrazone setup ...'
  zone:
    world:
    pos1:
      x:
      y:
      z:
    pos2:
      x:
      y:
      z:


#
status:
  # If players should be able to use the '/status' command
  enabled: true # Default: true


# The End-Event settings
# Use '/buildmc endevent allow true/false' to set if players should be able to enter the end dimension
end-event:
  # NOTE: Can be overwritten by the '/buildmc endevent' command
  allow-end: false # Default: false

  # List of entity types that should be blocked from going through end portals.
  # Done to prevent destruction of the spawn
  blocked-entities:
    - TNT
    - TNT_MINECART
    - CREEPER


# Some sounds that are used generally
sounds:
  mistake: "minecraft:block.note_block.snare" # Default: "minecraft:block.note_block.snare"
  success: "minecraft:block.note_block.bell" # Default: "minecraft:block.note_block.bell"
  notification: "minecraft:entity.item.pickup" # Default: "minecraft:entity.item.pickup"


# Here are all settings related to team claims.
# A team can use the claim-tool or the '/buildmc claim ...' command to create or remove their claims.
# On Claims, things like any explosion, withers, block breaking or opening containers don't work.
# Team players can give other players access to their claims using '/buildmc claim allow <player name>'.
claims:
  # If true, players can manage their team claims using '/claim ...'.
  # Admins can also set certain regions as server-claims that no one can do anything in
  enabled: true # Default: true

  # If true, all claim data will be writen to disk when the server saves the overworld.
  # Only change this to false if you really need to
  save-on-world-save: true # Default: true

  # The amount of chunks each player can claim
  player-max-chunk-claim-amount: 1024 # Default: 1024
  # The amount of chunks each team can claim
  team-max-chunk-claim-amount: 1024 # Default: 1024

  # Settings related to the claim-tool. The claim-tool (if enabled) can be obtained using '/buildmc claimtool'
  tool:
    # The item used for the claim-tool
    tool-item: "carrot_on_a_stick" # Default: "carrot_on_a_stick"

    # If true, players even without permissions can get the claim-tool using '/buildmc claimtool'
    enable-give-command: true # Default: true

    # Limits the maximum size in chunks of the selection
    # If smaller than 0, the limit will be disabled
    limit-selection: 8 # Default: 8

  # What aspects are protected when claimed
  protections:
    # Players cannot break blocks
    player-break: true
    # Players cannot place blocks
    player-place: true

    # Players cannot open containers (e.g. Chests, Barrels...)
    containers: true

    # Players cannot pick up items
    item-pickup: false

    # Players cannot drop items
    item-drop: false

    # Players cannot edit signs
    sign-editing: true

    # Players can't use splash potions
    splash-potions: true

    # Players can't enter vehicles
    vehicle-enter: true

    # Players can't use buckets
    bucket-usage: true

    # Players can't use frost walker enchantment
    frostwalker: true

    # Players can't trigger sculk sensors
    sculk-sensor: true

    # Prevents pistons from moving into claims and pulling out of claims
    piston-movement-across-claim-borders: true

    # Interaction related protections
    interactions:
      jukebox: true

      levers: true
      buttons: true
      repeaters: true
      comparators: true
      daylight-sensors: true

      tripwire: true
      pressure-plates: true
      trapdoors: true
      doors: true
      fence-gates: true
      farmland: true

      campfire: true
      bells: true
      attach-leash: true
      bonemeal: true
      beehives: true
      nametags: true
      item-frames: true
      candle-extinguish: true
      hanging-entities: true
      light-tnt: true
      armor-stand: true
      tame-entity: true
      shear-entity: true

    projectile-interactions: true

    fishing: true

    # Damage related protections
    damage:
      # Cancels all damage dealt by players to protected entities
      entity-damage: true
      # Allows players to be damaged by other players
      exclude-players: true

      # Blocks cannot be destroyed from explosions
      explosion-block-damage: true
      # Entities cannot get damage from explosions
      explosion-entity-damage: true

    # Entities in entity-modifications cannot modify blocks
    entity-modifications:
      wither: true
      enderman: false
      ravager: false

disable-commands: true
disabled-commands:
  # Reload commands. WE DO NOT RECOMMEND USING THIS COMMAND. PLEASE RESTART THE SERVER.
  - "bukkit:reload"
  - "bukkit:rl"
  - "bukkit:bukkitreload"

  # Seed command. This is done to prevent the seed from being accessible, even to admins.
  - "minecraft:seed"

  # Dangerous server control
  - "minecraft:save-off"

player-head:
  # When true, players will drop their head on death.
  on-death: true # Default: true
